# Numpy

In [1]:
##!pip install numpy

In [2]:
import numpy as np

###  zeros()

 - 괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화

In [3]:
y = np.zeros(shape=(10, 2), dtype=np.int8)
# y = np.zeros(10)
print(y)


x = np.array([1, 2, 3])
print(type(x), x)
x.shape
# propoty 속성

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
<class 'numpy.ndarray'> [1 2 3]


(3,)

In [4]:
np.zeros(3)
# 배열형태로 0 3번찍힘

array([0., 0., 0.])

###  mean() : 배열에 저장된 원소들의 평균값을 계산

In [5]:
import numpy as np

list_1 = [1, 2, 3]
x = np.array(list_1)
np.mean(x)
x.mean()
x.shape
# 3행

(3,)

### array() 
 - Numpy 형식으로 배열의 원소를 입력할 때는 반드시 리스트 형식으로 입력


In [6]:
x = np.array([1, 2, 3])
y = np.array((1, 2, 3))
z = np.array({12, 3, 4})
a = np.array({'a':'b', 'c':'d'})
print(x, y, z, a)


[1 2 3] [1 2 3] {3, 12, 4} {'a': 'b', 'c': 'd'}


### reshape()
 - 배열을 원하는 모양으로 생성

In [7]:
import numpy as np
a = [1,2,3,4,5,6]
b = np.reshape(a,(3, 2))
print(b, b.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [8]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b, b.shape, '\n')
print(c, c.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


 - reshape() 3차원 변환

In [9]:
a = np.arange(8)
print(a,'\n')

a = np.arange(1,9)
print(a,'\n')

b = a.reshape(2,2,2)
print(b)

[0 1 2 3 4 5 6 7] 

[1 2 3 4 5 6 7 8] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
a = np.arange(1,13)
print(a,'\n')

b = a.reshape(3,2,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## reshape 의미

#### reshape를 활용하는 경우를 보다 보면 입력인수로 -1이 들어간 경우가 종종 있다. reshape()의 ‘-1’이 의미하는 바는, 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

In [11]:
x = np.arange(12)
y = x.reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [13]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
print(x.reshape(-1,3), x.reshape(-1,3).shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)


### ones()
 -  배열을 1의 값들로 채움

In [15]:
y = np.ones([3, 4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
y = np.ones([4, 3])
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
y = np.ones([4, 3]) * 2
print(y)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [18]:
y = np.ones([4, 3]) * 0.3
print(y)

[[0.3 0.3 0.3]
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]]


### Numpy 배열의 슬라이싱

In [19]:
list1 = [[1, 11], [2, 12], [3, 13], [4, 14] ]
print(list1[:][1])
#print(list1[:,1])

[2, 12]


In [20]:
list1 = [[1, 11], [2, 12], [3, 13], [4, 14] ]
arr = np.array(list1)
print(arr.shape,'\n')
print(arr,'\n')
print(arr[:,1],'\n')
print(arr[:][1],'\n')
print(arr[1][1],'\n')
print(arr[:][1],'\n')
print(arr[1:4],'\n')

(4, 2) 

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]] 

[11 12 13 14] 

[ 2 12] 

12 

[ 2 12] 

[[ 2 12]
 [ 3 13]
 [ 4 14]] 



### math 모듈의 sqrt() 와 numpy 모듈의 sqrt() 비교

In [21]:
import math
math.sqrt(2)
# math.sqrt([2,3,4])

1.4142135623730951

In [22]:
import numpy as np
print(np.sqrt([2]))
print(np.sqrt([2,3,4]))

[1.41421356]
[1.41421356 1.73205081 2.        ]


In [23]:
import numpy as np

x = np.zeros(15)
x
x.reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
y = np.zeros([5,3])
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#(3, 5)형태로 reshape
z = y.reshape([3,5])
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
z = y.reshape([3,5])
z += 4
z

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

### 전치행렬
 - transpose()
 - 행렬의 값들을 주대각선을 기준으로 위치를 바꾼 행렬을 의미
 - 행과 열을 교환하여 얻어지는 행렬

In [27]:
import numpy as np
ary = np.array([[1, 2],[3, 4]])
print(ary, '\n')

trans_ary = ary.transpose()
print(trans_ary)

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


In [28]:
ary = np.array([[1, 2, 5],[3, 4, 6]])
print(ary, '\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2 5]
 [3 4 6]] 

[[1 3]
 [2 4]
 [5 6]]


### 2개 배열에 대한 연산
 - 2개 배열에 저장된 내용을 인덱스별로 계산
 - 선형대수학의 사칙연산과 동일하게 작동
 - 곱셈도 같은 원리로 동작

In [29]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x+y)
print(x*y)
print(x/y)
print(x**y)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [30]:
x = np.array([1, 2, 3])
x += 1
print(x)

[2 3 4]


In [31]:
x = np.array([1, 2, 3])
x **= 2
print(x)
print(type(x))
print(list(x))
print(type(list(x)))

[1 4 9]
<class 'numpy.ndarray'>
[1, 4, 9]
<class 'list'>


### 인덱싱

In [32]:
X = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(X[1])
print(X[:, 1])

[4 5 6]
[2 5 8]


### 2개의 Numpy 배열 간의 계산

In [33]:
X = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
Y = np.array([[2,3,4] , [5,6,7] , [8,9,10]])
print(X[:,1]+Y[:,1])

[ 5 11 17]


In [34]:
# X의 1행 + Y의 3행
X = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
Y = np.array([[2,3,4] , [5,6,7] , [8,9,10]])
print(X[0])
print(Y[2])
print("result : ",X[0] + Y[2])

[1 2 3]
[ 8  9 10]
result :  [ 9 11 13]


In [35]:
# X의 1행 + Y의 3행
X = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
Y = np.array([[2,3,4] , [5,6,7] , [8,9,10]])
print(X[0:,1:2])
print(Y[2,:])
print("result : ",X[0:,1:2] * Y[2])

[[2]
 [5]
 [8]]
[ 8  9 10]
result :  [[16 18 20]
 [40 45 50]
 [64 72 80]]


In [36]:
# X의 1행 + Y의 3행
X = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
Y = np.array([[2,3,4] , [5,6,7] , [8,9,10]])
print(X[:,1]*Y[2,:])

[16 45 80]


In [37]:
a = np.array([10, 20, 30, 40, 60])

b = a > 30
print(b)

[False False False  True  True]


### random()

In [38]:
import numpy as np

ary = np.random.random(5)
print(ary)

[0.1504308  0.88818521 0.23825191 0.74442167 0.81944586]


In [39]:
# [0, 1) 범위에서 균일한 분포를 갖습니다.
a = np.random.rand(5)
print(a, '\n')

b = np.random.rand(2, 3)
print(b,b.shape)

[0.79416352 0.00687288 0.46293376 0.93642825 0.77894456] 

[[0.21057218 0.63935225 0.35814225]
 [0.66162666 0.49949008 0.66399951]] (2, 3)


In [40]:
a = np.random.randint(2, size=5)
print(a)

b = np.random.randint(2, 4, size=5)
print(b)

c = np.random.randint(1, 5, size=(2, 3))
print(c)

[1 0 0 0 1]
[3 2 3 2 2]
[[4 3 2]
 [3 3 3]]


In [41]:
a = np.random.rand(5)
a > 0.12

array([ True,  True, False,  True,  True])

### random.seed()

In [42]:
np.random.seed(0)

print(np.random.rand(2, 3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [43]:
np.random.seed(0)
a = np.random.rand(5)
print(a > 0.12)
print(np.all(a>0.12))

[ True  True  True  True  True]
True


### any()와 all()의 비교

In [44]:
a = np.random.rand(5)
print(a>0.12)
print(np.all(a>0.12))

[ True  True  True  True  True]
True


In [45]:
a = np.random.rand(5)
print(a>0.9)
print(np.any(a>0.9))

[False False False  True False]
True


In [46]:
import numpy as np
np.random.seed(0)
a = np.random.rand(7)
print(a)
a = np.random.rand(7)
print(a)
c = np.random.rand(7)
print(c)
np.random.seed(3)
c = np.random.rand(7)
print(c)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721]
[0.891773   0.96366276 0.38344152 0.79172504 0.52889492 0.56804456
 0.92559664]
[0.07103606 0.0871293  0.0202184  0.83261985 0.77815675 0.87001215
 0.97861834]
[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
 0.12558531]


### linspace()
 - 시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분
 - 0과 12를 포함한 그 사이의 값들을 선형적으로 분배하여 모두 4개의원소를 갖는 배열을 생성
 - np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)

In [47]:
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

In [48]:
np.linspace(0, 13, 5)

array([ 0.  ,  3.25,  6.5 ,  9.75, 13.  ])

In [49]:
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

In [50]:
# 샘플간의 간격
np.linspace(2, 12, 5, retstep=True) 

(array([ 2. ,  4.5,  7. ,  9.5, 12. ]), 2.5)

In [51]:
# 마지막 제외
np.linspace(2, 12, 5, endpoint=False) 

array([ 2.,  4.,  6.,  8., 10.])